### ISSUE TITLE
Is there a way to learn about new seminars?

### ISSUE THREAD

**Issue by k4rtik** [uchicago-computation-workshop/tom_griffiths#1]
Reposting here as I didn't hear anything back at https://github.com/uchicago-computation-workshop/CALENDAR/issues/1

---

I am aware that @nnickels or @jmausolf send out email announcements on various existing lists within the University, but is there a public mailing list that is used to announce the calendar and weekly seminars that people could just subscribe to?

It's fairly easy to create such a list using https://lists.uchicago.edu/web/create_list_request and ask interested people to subscribe to that list.

Thanks

**Comment by nnickels** [comment]
@k4rtik the calendar and weekly seminars can be followed both on the [MACSS website](https://macss.uchicago.edu/content/computation-workshop) as well as on the [calendar repository](https://github.com/uchicago-computation-workshop/CALENDAR). Try subscribing to the calendar repository if you would like to be alerted when the calendar is updated. Alternatively, send me an email at nnickels@uchicago.edu if you're interested in being added to the list directly.

**Comment by k4rtik** [comment]
Hi, @nnickels thanks, those solutions work for people interested in the seminars but do not help people who are not interested in them and feel spammed by emails sent out to larger mailing lists like my own department's CS list. I am one of the PhD student representatives in Computer Science and am working toward an effort to reduce unnecessary email sent out to us.

If there were a public email list for these seminars (which IMHO is the right technical solution to advertising for such talks), I could help you advertise it to people from CS interested in the seminars so only people interested in the seminars receive the emails instead of everyone feeling spammed.

**Comment by nnickels** [comment]
Thanks - we'll look into it for next year!

**Comment by k4rtik** [comment]
Looks like a list has been created: https://lists.uchicago.edu/web/info/computational_social_sciences

(leaving the link here for posterity)
